---
# tasks file for metricbeat_install
- name: Gather private IPs for all Elasticsearch
  set_fact:
    elastic_nodes: >-
      {{
        groups['tag_app_elastic']
        | map('extract', hostvars, 'ansible_default_ipv4')
        | selectattr('address', 'defined')
        | map(attribute='address')
        | map('regex_replace', '^', '"http://')
        | map('regex_replace', '$', ':9200"')
        | list
      }}
  delegate_to: localhost
  run_once: true

- name: Install metricbeat packages
  ansible.builtin.apt:
    name: metricbeat
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable elasticsearch module
  ansible.builtin.shell: metricbeat modules enable elasticsearch
  register: __metricbeat_modules_enable_elasticsearch
  changed_when: __metricbeat_modules_enable_elasticsearch.rc != 0

- name: Configure metricbeat
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: '^(.*)hosts:(.*)$'
    line: '\1hosts: [{{ elastic_nodes | join(", ") }}]'
    backrefs: true
  with_items:
    #- /etc/metricbeat/metricbeat.yml
  - /etc/metricbeat/modules.d/elasticsearch.yml
  notify: restart metricbeat