---
# tasks file for metricbeat_install
- name: shell tag_app_elastic
  shell: aws ec2 describe-instances --filters "Name=tag:app,Values=elastic" --query "Reservations[*].Instances[*].PrivateIpAddress" --output text
  register: shelloutput
  delegate_to: localhost
  become_user: ubuntu
  run_once: true
  changed_when: shelloutput.rc != 0

- name: Gather private IPs for all Elasticsearch
  set_fact:
    elastic_nodes: >-
      {{
        shelloutput.stdout_lines
        | map('regex_replace', '^', '"http://')
        | map('regex_replace', '$', ':9200"')
        | list
      }}
  delegate_to: localhost
  run_once: true

# - name: Gather private IPs for all Elasticsearch
#   set_fact:
#     elastic_nodes: >-
#       {{
#         groups['tag_app_elastic']
#         | map('extract', hostvars, 'ansible_default_ipv4')
#         | selectattr('address', 'defined')
#         | map(attribute='address')
#         | map('regex_replace', '^', '"http://')
#         | map('regex_replace', '$', ':9200"')
#         | list
#       }}
#   delegate_to: localhost
#   run_once: true

- name: Install metricbeat packages
  ansible.builtin.apt:
    name: metricbeat
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Configure metricbeat
  ansible.builtin.lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    regexp: '^(.*)hosts:(.*)localhost:9200(.*)$'
    line: '\1hosts: [{{ elastic_nodes | join(", ") }}]'
    backrefs: true
  notify: restart metricbeat

- name: Enable elasticsearch module
  ansible.builtin.shell: "metricbeat modules enable {{ item }}"
  loop: "{{metricbeat_modules}}"
  changed_when: shelloutput.rc != 0